services:
    db:
      image: postgres:16
      environment:
        POSTGRES_USER: ${PGUSER}
        POSTGRES_PASSWORD: ${PGPASSWORD}
        POSTGRES_DB: ${PGDB}
      volumes:
        - postgres_data:/var/lib/postgresql/data

    app:
      build: .
      ports:
        - "8000:8000"
      environment:
        PGUSER: ${PGUSER}
        PGPASSWORD: ${PGPASSWORD}
        PGHOST: db
        PGPORT: 5432
        PGDB: ${PGDB}
        GEMINI_API_KEY: ${GEMINI_API_KEY}
      depends_on:
        - db

volumes:
  postgres_data: